```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(313)
# library(imager)
# library(spam)
# library(Matrix)
# library(lme4)
# library(splines)
# library(magrittr)
# library(imager)
# library(ggplot2) 
# library(fields)
library(imager)
library(ggplot2) 
library(plotly)
library(splines)
library(spam)
library(Matrix)
library(lme4)
library(rgl)
library(fields)
library(survival)
library(smoothie) 

col_shoe <- 307 # 307 is the number of columns in each shoe
row_shoe <- 395 # 395 is the number of rows in each shoe
num_shoe <- 387  # 387 is the number of shoes but 386 is the number of shoes with RACs - shoe 127 has no RACS

rel_col_shoe <- 150  # out of the 307 columns only 150 are relevant (contain non zero pixels in some shoes)
rel_row_shoe <- 300  # out of the 395 rows only 300 are relevant (contain non zero pixels in some shoes)
rel_x_cord <- 0.25 # using coordinates as in the locations_data.CSV file the relevant x coordinates are between -.25 and 0.25
rel_Y_cord <- 0.5 # the relevant Y coordinates are between -0.5 and 0.5
```

```{r }

source("config.R")

MODEL_FEATURE <- "NEW_X_NS_XY"
# MODEL_FEATURE <- "NEW_X_NS_XY"
# MODEL_FEATURE <- "NULL_MODEL"
# MODEL_FEATURE <- "NS_XY"
# MODEL_FEATURE <- "CMD_MODEL"
# MODEL_FEATURE <- "NAIVE_MODEL"  

```



```{r }


file_name <- paste(ROOT_PATH, "statistical_model/dataset/dataCC_distance.csv", sep = "")
dataCC <- read.csv(file_name, header = TRUE)
dataCC <- subset(dataCC, select = c("n_Acc", "x", "y", "shoe", "row_number", "horiz_dist", "new_x"))
file_name <- paste(ROOT_PATH, "data/all_cont.csv", sep = "")
allcont <- read.csv(file_name, header = TRUE)
```




```{r}
# Helper function for NAIVE_MODEL
Naive <- function(cumRAC, cumContact, areaShoe) {
  Naivemat <- cumRAC / cumContact
  Naivemat[areaShoe==0] <- NA
  est <- kernel2dsmooth(Naivemat, kernel.type="boxcar", n=21)
  est[areaShoe==0] <- NA
  return(est)
}

Random <- function(nknotsx = 3, nknotsy = 5, dat = dataCC, model_feat = MODEL_FEATURE, initial_values) {
  
  common_formula <- as.formula("n_Acc ~ (1 | shoe)")
  
  
  knotsx <- as.numeric(quantile(dat$x,1:nknotsx/(1+nknotsx)))
  knots_new_x <- as.numeric(quantile(dat$new_x,1:nknotsx/(1+nknotsx)))
  knotsy <-as.numeric(quantile(dat$y,1:nknotsy/(1+nknotsy)))
  # knots_distance not currently used by any model, but kept for potential future use
  # knots_distance <-as.numeric(quantile(dat$horiz_dist,1:2/(3)))  # Using horiz_dist if needed
  shoe<-dat$shoe
  
  initial_values <- c(parameter1 = 0)  # Adjust these values
  est <- NULL
  if(model_feat == 'NS_XY'){
    est<- glmer(n_Acc ~ ns(dat$x,knots=knotsx):ns(dat$y,knots=knotsy) + (1 | shoe), data = dat, family = binomial(link = "logit"), control =glmerControl(optimizer="nlminbwrap"))
  }
  else if(model_feat == 'NEW_X_NS_XY'){
    est<- glmer(n_Acc ~ ns(dat$new_x,knots=knots_new_x):ns(dat$y,knots=knotsy) + (1 | shoe),data = dat, family = binomial(link = "logit"), control =glmerControl(optimizer="nlminbwrap"))
  }
  else if(model_feat == 'EMPTY_MODEL'){
    est<- glmer(n_Acc ~ (1 | shoe),data = dat, family = binomial(link = "logit"), control =glmerControl(optimizer="nlminbwrap"))
  }
  else if(model_feat == 'CMD_MODEL'){
    est<- clogit(dat$n_Acc~  ns(dat$x,knots=knotsx):ns(dat$y,knots=knotsy)+strata(shoe) , data=dat)
  }
  else if(model_feat == 'NAIVE_MODEL'){
    # Load sumacci and sumcont (saved in dataCC_1.Rmd)
    file_name <- paste(ROOT_PATH, "data/sumacci.csv", sep = "")
    sumacci <- as.matrix(read.csv(file_name, header = TRUE))
    file_name <- paste(ROOT_PATH, "data/sumcont.csv", sep = "")
    sumcont <- as.matrix(read.csv(file_name, header = TRUE))
    est <- Naive(sumacci, sumcont, allcont)
  }
  else { stop("Invalid model_feat value")}
  
  cat("file_saving")
  file_name <- paste(ROOT_PATH, "statistical_model/saved_models/",MODEL_FEATURE,".rds", sep = "")
  saveRDS(est, file = file_name)
  return(est)
}
get_initial_values <- function(){
  #NOT USED AND NOT UP TO DATE (07/01/25)
  # seems not to be used .. Maybe I created that for other models
  file_name <- paste(ROOT_PATH, "statistical_model/saved_models/NS_XY.rds", sep = "")
  naomi_model <- readRDS(file = file_name)
  fixed_effects <- fixef(naomi_model) # View the fixed effects coefficients print(fixed_effects) 
  vals <- as.list(fixed_effects)
  if (grepl("DUMMY", MODEL_FEATURE)){ 
  vals <- c(vals, list(dummy_0to1 = 0, dummy_1to2 = 0))}
  else if (grepl("BIN_CAT", MODEL_FEATURE)){
    vals <- c(vals, list(bin_cat = 0))
  }
  return(vals) 
}

rand<-Random(dat=dataCC,initial_values=get_initial_values())
```



```{r}
```
